name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Tentukan versi Node.js yang ingin digunakan

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test  # Sesuaikan perintah ini jika menggunakan framework pengujian lain seperti Jest atau Mocha
